name: Update ladder

on:
  workflow_dispatch:
  schedule:
    - cron: "*/3 * * * *" # every midnight

jobs:
  Update-Ladder:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run main.py to update leaderboard
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python app/main.py

      - name: List changes
        run: git status
