name: Update ladder

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes

jobs:
  Update-Ladder:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run main.py to update leaderboard
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PYTHONUNBUFFERED: "1"
        run: python app/main.py

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "Github Actions"
          git add .
          git commit -m "Update ladder w/ Workflow"
          git pull --rebase

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
